import type { Job } from '../features';

export interface ShareableApplication {
  id: string;
  title: string;
  company: string;
  location: string;
  salary: string | null;
  description: string | null;
  url: string | null;
  status: string;
  priority: string;
  createdAt: string;
  updatedAt: string;
}

export class ApplicationSharing {
  static generateShareLink(application: ShareableApplication): string {
    const baseUrl = window.location.origin;
    const encodedData = btoa(JSON.stringify(application));
    return `${baseUrl}/shared/application/${encodedData}`;
  }

  static generateShareText(application: ShareableApplication): string {
    return `🎯 ${application.title} at ${application.company}\n\n📍 ${application.location}\n💰 ${application.salary || 'Not specified'}\n\n📝 ${application.description || 'No description available'}\n\n🔗 ${application.url || 'No URL available'}\n\nShared via ApplyFlow - Track your job applications efficiently!`;
  }

  static async shareViaEmail(application: ShareableApplication, recipientEmail?: string): Promise<void> {
    const subject = `Job Application: ${application.title} at ${application.company}`;
    const body = this.generateShareText(application);

    const mailtoUrl = recipientEmail
      ? `mailto:${recipientEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
      : `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;

    window.open(mailtoUrl, '_blank');
  }

  static async shareViaLinkedIn(application: ShareableApplication): Promise<void> {
    const text = `Check out this opportunity: ${application.title} at ${application.company} ${application.location}`;
    const url = application.url || window.location.href;

    const linkedinUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}&summary=${encodeURIComponent(text)}`;
    window.open(linkedinUrl, '_blank');
  }

  static async shareViaTwitter(application: ShareableApplication): Promise<void> {
    const text = `🎯 ${application.title} at ${application.company} ${application.location} #JobSearch #Career`;
    const url = application.url || window.location.href;

    const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`;
    window.open(twitterUrl, '_blank');
  }

  static async copyToClipboard(application: ShareableApplication): Promise<void> {
    try {
      const text = this.generateShareText(application);
      await navigator.clipboard.writeText(text);
      return Promise.resolve();
    } catch {
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = this.generateShareText(application);
      textArea.style.position = 'fixed';
      textArea.style.opacity = '0';
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();

      try {
        document.execCommand('copy');
        document.body.removeChild(textArea);
        return Promise.resolve();
      } catch {
        document.body.removeChild(textArea);
        return Promise.reject(new Error('Failed to copy to clipboard'));
      }
    }
  }

  static async exportAsJSON(application: ShareableApplication): Promise<void> {
    const dataStr = JSON.stringify(application, null, 2);
    const dataBlob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(dataBlob);

    const link = document.createElement('a');
    link.href = url;
    link.download = `application-${application.company.replace(/\s+/g, '-').toLowerCase()}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  static async exportAsPDF(application: ShareableApplication): Promise<void> {
    // This would require a PDF library like jsPDF
    // For now, we'll create a simple text-based representation
    const content = `
JOB APPLICATION DETAILS
======================

Position: ${application.title}
Company: ${application.company}
Location: ${application.location}
Salary: ${application.salary || 'Not specified'}
Status: ${application.status}
Priority: ${application.priority}

Description:
${application.description || 'No description available'}

URL: ${application.url || 'Not specified'}

Created: ${new Date(application.createdAt).toLocaleDateString()}
Updated: ${new Date(application.updatedAt).toLocaleDateString()}

---
Generated by ApplyFlow
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = `application-${application.company.replace(/\s+/g, '-').toLowerCase()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  static parseSharedApplication(encodedData: string): ShareableApplication | null {
    try {
      const decoded = atob(encodedData);
      return JSON.parse(decoded);
    } catch {
      return null;
    }
  }

  static createShareableApplication(job: Job): ShareableApplication {
    return {
      id: job.id,
      title: job.title,
      company: job.company,
      location: job.location,
      salary: job.salary || null,
      description: job.description || null,
      url: job.url || null,
      status: job.status,
      priority: job.priority,
      createdAt: job.createdAt,
      updatedAt: job.updatedAt,
    };
  }
}